### ISSUE TITLE
Request for pre-trained weights

### ISSUE THREAD

**Issue by jdfxzzy** [wenyu1009/RTSRN#2]
Hi, wenyu,
Thank you for sharing your great work! Could you please release your pre-trained weights to help us to better understand your model? Thanks!

**Comment by wenyu1009** [comment]
Thank you for your attention to our work. This project is in collaboration with China Merchants Bank and the checkpoint cannot be opened without their permission. However, the open-source code can reproduce the results. It is important to note that the size of the TextZoom dataset is only 64X16. This model can only process small-sized images.

**Comment by jdfxzzy** [comment]
OK, thank you for your reply!
