### ISSUE TITLE
关于先验分支

### ISSUE THREAD

**Issue by llvhjgtdl** [wenyu1009/RTSRN#3]
你好，请问你提供的代码是完整的吗？你说是以C3那篇作为基线，它使用的语言线索使用预训练的双向完型填空网络，但是你目前提供的代码中我没有看到相关的预训练模型

**Comment by llvhjgtdl** [comment]
在配置文件中

**Comment by wenyu1009** [comment]
现有代码是完整的，我们基于C3的github的代码复现的结果，但是作者仅给出了部分代码
https://github.com/zhaominyiz/C3-STISR/blob/2e3bbecd1d989136ffd963392b2aecec4b302257/model/c3.py#L391-L393
预训练的语言线索模型，C3的作者没有放出来。

**Comment by llvhjgtdl** [comment]
我知道它没提供预训练模型，所以我想问的是你是怎么用的这部分语言模型，直接加进去没用预训练也有效果？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wenyu1009/RTSRN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 下午4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wenyu1009/RTSRN] 关于先验分支 (Issue #3)





 
现有代码是完整的，我们基于C3的github的代码复现的结果，但是作者仅给出了部分代码
 https://github.com/zhaominyiz/C3-STISR/blob/2e3bbecd1d989136ffd963392b2aecec4b302257/model/c3.py#L391-L393
 预训练的语言线索模型，C3的作者没有放出来。

**Comment by wenyu1009** [comment]
是的，我这里是直接加进去使用。没做过这个实验的消融


在2023-12-20 ***@***.***写道：

我知道它没提供预训练模型，所以我想问的是你是怎么用的这部分语言模型，直接加进去没用预训练也有效果？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wenyu1009/RTSRN" ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 下午4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wenyu1009/RTSRN] 关于先验分支 (Issue #3)






现有代码是完整的，我们基于C3的github的代码复现的结果，但是作者仅给出了部分代码
https://github.com/zhaominyiz/C3-STISR/blob/2e3bbecd1d989136ffd963392b2aecec4b302257/model/c3.py#L391-L393
预训练的语言线索模型，C3的作者没有放出来。

**Comment by llvhjgtdl** [comment]
好滴感谢回复，祝好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月21日(星期四) 中午1:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wenyu1009/RTSRN] 关于先验分支 (Issue #3)





 是的，我这里是直接加进去使用。没做过这个实验的消融
 
 
 在2023-12-20 ***@***.***写道：
 
 我知道它没提供预训练模型，所以我想问的是你是怎么用的这部分语言模型，直接加进去没用预训练也有效果？
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "wenyu1009/RTSRN" ***@***.***&amp;gt;;
 发送时间:&amp;nbsp;2023年12月20日(星期三) 下午4:18
 ***@***.***&amp;gt;;
 ***@***.******@***.***&amp;gt;;
 主题:&amp;nbsp;Re: [wenyu1009/RTSRN] 关于先验分支 (Issue #3)
 
 
 
 
 
 
 现有代码是完整的，我们基于C3的github的代码复现的结果，但是作者仅给出了部分代码
 https://github.com/zhaominyiz/C3-STISR/blob/2e3bbecd1d989136ffd963392b2aecec4b302257/model/c3.py#L391-L393
 预训练的语言线索模型，C3的作者没有放出来。

**Comment by llvhjgtdl** [comment]
> 是的，我这里是直接加进去使用。没做过这个实验的消融 在2023-12-20 ***@***.***写道： 我知道它没提供预训练模型，所以我想问的是你是怎么用的这部分语言模型，直接加进去没用预训练也有效果？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wenyu1009/RTSRN" ***@***.***&gt;; 发送时间:&nbsp;2023年12月20日(星期三) 下午4:18 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wenyu1009/RTSRN] 关于先验分支 (Issue #3) 现有代码是完整的，我们基于C3的github的代码复现的结果，但是作者仅给出了部分代码 https://github.com/zhaominyiz/C3-STISR/blob/2e3bbecd1d989136ffd963392b2aecec4b302257/model/c3.py#L391-L393 预训练的语言线索模型，C3的作者没有放出来。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

能问下你是直接再整个训练过程都用到了这个先验分支吗？因为据我所知这个先验分支训练多了效果反而不好

**Comment by wenyu1009** [comment]
> > 是的，我这里是直接加进去使用。没做过这个实验的消融 在2023-12-20 _**@**_._**写道： 我知道它没提供预训练模型，所以我想问的是你是怎么用的这部分语言模型，直接加进去没用预训练也有效果？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "wenyu1009/RTSRN" _**@**_.**_>; 发送时间: 2023年12月20日(星期三) 下午4:18 _**@**_._**>; _**@**_.**__**@**_._**>; 主题: Re: [wenyu1009/RTSRN] 关于先验分支 (Issue #3) 现有代码是完整的，我们基于C3的github的代码复现的结果，但是作者仅给出了部分代码 https://github.com/zhaominyiz/C3-STISR/blob/2e3bbecd1d989136ffd963392b2aecec4b302257/model/c3.py#L391-L393 预训练的语言线索模型，C3的作者没有放出来。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.**_> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 能问下你是直接再整个训练过程都用到了这个先验分支吗？因为据我所知这个先验分支训练多了效果反而不好

是的都使用到了这个先验分支。
