### ISSUE TITLE
关于实验

### ISSUE THREAD

**Issue by llvhjgtdl** [wenyu1009/RTSRN#5]
看了这篇的实验部分，关于消融实验您提到是用CRNN评估三个数据集的均值进行对比，但是你Table3中的Baseline不就是TSRN吗为啥它的ACC是51.7没这么高把？我看他论文中写的CRNN的average是41.4啊

**Comment by wenyu1009** [comment]
本文的baseline 是C3-STISR这篇工作，在论文的3.1节中有说明。
实验结果上，由于C3-STISR仅公布了核心代码，没有提供预训练后的部分模块。我们的baseline为根据该核心代码复现的结果，主要差别在于部分模块没有进行预训练。复现的代码我们跑的结果为51.7，这就是论文中basline的结果。
