### ISSUE TITLE
关于对比实验部分

### ISSUE THREAD

**Issue by JeremyCoool** [wenyu1009/RTSRN#6]
无法正确运行对比实验，如SRCNN，请问作者在开展对比实验过程中采用的是怎样的指令，能否提供一下！感谢！！

**Comment by JeremyCoool** [comment]
感觉在代码中阉割了进行对比实验部分的代码，请问能否提供完整的接口文件~

**Comment by wenyu1009** [comment]
该库代码仅包含我们提出模型的训练、测试和可视化代码。其他模型的请参考其论文提供源码。
这个版本的代码，也确实比较冗余，较难修改==

**Comment by JeremyCoool** [comment]
感谢您的回复和对这项工作的贡献，事实上我正在尝试复现对比实验的过程中出现了一些问题，主要体现在eval()函数的修改上。由于C3这个baseline的仓库已关闭，很多代码难以进行。能否再次请求您提供一下完整的代码版本，我对这项工作非常感兴趣，能否可以通过邮箱1019977862@qq.com发送给我，这对我真的很重要！
